# Generated by Django 5.2.3 on 2025-07-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # Add teacher field
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.teacher'),
        ),
        # Add observation_type field
        migrations.AddField(
            model_name='schedule',
            name='observation_type',
            field=models.CharField(choices=[('formal', 'Formal Observation'), ('walk-through', 'Walk-through')], default='formal', max_length=20),
        ),
        # Make observation_group nullable
        migrations.AlterField(
            model_name='schedule',
            name='observation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.observationgroup'),
        ),
        # Update status choices
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=255),
        ),
    ]