# Generated by Django 5.2.3 on 2025-06-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationgroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='api.users'),
        ),
    ]
