# Generated by Django 5.2.3 on 2025-08-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_schedule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether initial scheduling notification was sent'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether reminder notification was sent'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When reminder was sent', null=True),
        ),
    ]
