# Generated by Django 5.2.3 on 2025-08-18 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_notification_fields_to_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved by Teacher'), ('review_requested', 'Review Requested'), ('revised', 'Revised')], default='draft', max_length=20)),
                ('score_classroom_management', models.IntegerField(default=3, help_text='Classroom management score (1-5)')),
                ('score_content_knowledge', models.IntegerField(default=3, help_text='Content knowledge score (1-5)')),
                ('score_student_engagement', models.IntegerField(default=3, help_text='Student engagement score (1-5)')),
                ('score_teaching_methods', models.IntegerField(default=3, help_text='Teaching methods score (1-5)')),
                ('score_assessment', models.IntegerField(default=3, help_text='Assessment score (1-5)')),
                ('score_professionalism', models.IntegerField(default=3, help_text='Professionalism score (1-5)')),
                ('strengths', models.JSONField(default=list, help_text='List of observed strengths')),
                ('areas_for_improvement', models.JSONField(default=list, help_text='List of areas for improvement')),
                ('overall_comments', models.TextField(blank=True, help_text='General observations and feedback')),
                ('lesson_objectives', models.TextField(blank=True, help_text='Lesson objectives observed')),
                ('observation_notes', models.TextField(blank=True, help_text='Additional observation notes')),
                ('action_step_category', models.CharField(blank=True, choices=[('internalization', 'Internalization'), ('year_long_pacing', 'Year-Long Pacing'), ('lesson_pacing', 'Lesson Pacing'), ('student_engagement', 'Student Engagement'), ('instructional_methods', 'Instructional Methods'), ('assessment', 'Assessment'), ('classroom_management', 'Classroom Management'), ('content_knowledge', 'Content Knowledge'), ('professional_development', 'Professional Development')], max_length=50)),
                ('action_step', models.TextField(blank=True, help_text='Specific recommended action step')),
                ('overall_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], max_length=20)),
                ('teacher_response_date', models.DateTimeField(blank=True, null=True)),
                ('teacher_response_comments', models.TextField(blank=True, help_text="Teacher's response or review request")),
                ('revision_history', models.JSONField(default=list, help_text='History of revisions')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_feedback', to='api.users')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.schedule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='api.teacher')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_reason', models.TextField(help_text='Reason for the revision')),
                ('previous_data', models.JSONField(help_text='Previous feedback data before revision')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.feedback')),
                ('revised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'verbose_name': 'Feedback Revision',
                'verbose_name_plural': 'Feedback Revisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
