# Generated by Django 5.2.3 on 2025-08-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedback_feedbackrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='office_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
